Repository gitcowor/prixy, pull requests merged in 2018-07, with the labels that each got.

#4 Test2 brance ' master
  index.html
  style.css
Labels: enhancement

#8 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: work

#20 fixes some things
  index.html
  warns/index.js
Labels: Star Luck, to merge

#21 I fixed some things with outdated browser message
  index.html
Labels: enhancement, review required
